python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
python cpuboard_client_1.py &
